name: simple_observable
description: A debouncer and throttle that works with `Future`s, `Stream`s, and callbacks.
version: 0.3.0+1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/simple_observable

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test: ^1.0.0
