name: simple_observable
description: Observe value changes using a Future, Stream, and/or a callback.
version: 1.1.0+2
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/simple_observable

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test: ^1.0.0
