name: simple_observable
description: Observe value changes using a Future, Stream, and/or a callback.
version: 2.0.0
homepage: https://github.com/jifalops/simple_observable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test: ^1.0.0
